sudo: false
language: node_js
node_js:
  - "4"
  - "5"

# Directories we want to cache between each build
cache:
  apt: true
  directories:
    - 'node_modules'
addons:
  # System install
  apt:
    sources:
      - 'ubuntu-toolchain-r-test'
    packages:
      - 'gcc-4.8'
      - 'g++-4.8'
env:
  - 'CXX=g++-4.8'
